src/Web/CarDealer.Web/Controllers/DashboardController.cs
namespace CarDealer.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using CarDealer.Data.Models;
    using CarDealer.Services.Data;
    using CarDealer.Web.ViewModels.Dashboard;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class DashboardController : BaseController
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ISalesService salesService;

        public DashboardController(
            UserManager<ApplicationUser> userManager,
            ISalesService salesService)
        {
            this.userManager = userManager;
            this.salesService = salesService;
        }

        public async Task<IActionResult> Index()
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var userSales = await this.salesService.GetUserDashboardSalesByUserId(user.Id);

            var viewModel = new DashboardViewModel();
            viewModel.UserFirstName = user.FirstName;
            viewModel.UserLastName = user.LastName;
            viewModel.UserCreatedOn = user.CreatedOn;
            viewModel.Sales = userSales.ToList();

            return this.View(viewModel);
        }
    }
}

src/Web/CarDealer.Web/Controllers/SalesController.cs
namespace CarDealer.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;

    using CarDealer.Common;
    using CarDealer.Data.Models;
    using CarDealer.Services.Data;
    using CarDealer.Web.ViewModels.InputModels.Sales;
    using CarDealer.Web.ViewModels.Sales;

    using GoogleReCaptcha.V3.Interface;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    using Newtonsoft.Json;

    public class SalesController : BaseController
    {
        private readonly IWebHostEnvironment webHostEnvironment;
        private readonly ICarsService carsService;
        private readonly ISalesService salesService;
        private readonly ICategoriesService categoriesService;
        private readonly IMakesService makesService;
        private readonly IModelsService modelsService;
        private readonly IFuelTypesService fuelTypesService;
        private readonly IEuroStandartsService euroStandartsService;
        private readonly IGearboxesService gearboxesService;
        private readonly IColorsService colorsService;
        private readonly ICountriesService countriesService;
        private readonly ICitiesService citiesService;
        private readonly ICaptchaValidator captchaValidator;
        private readonly UserManager<ApplicationUser> userManager;

        public SalesController(
            IWebHostEnvironment webHostEnvironment,
            ICarsService carsService,
            ISalesService salesService,
            ICategoriesService categoriesService,
            IMakesService makesService,
            IModelsService modelsService,
            IFuelTypesService fuelTypesService,
            IEuroStandartsService euroStandartsService,
            IGearboxesService gearboxesService,
            IColorsService colorsService,
            ICountriesService countriessService,
            ICitiesService citiesService,
            UserManager<ApplicationUser> userManager,
            ICaptchaValidator captchaValidator)
        {
            this.webHostEnvironment = webHostEnvironment;
            this.carsService = carsService;
            this.salesService = salesService;
            this.categoriesService = categoriesService;
            this.makesService = makesService;
            this.modelsService = modelsService;
            this.fuelTypesService = fuelTypesService;
            this.euroStandartsService = euroStandartsService;
            this.gearboxesService = gearboxesService;
            this.colorsService = colorsService;
            this.countriesService = countriessService;
            this.citiesService = citiesService;
            this.userManager = userManager;
            this.captchaValidator = captchaValidator;
        }

        [Authorize]
        public async Task<IActionResult> Create(int countryId)
        {
            if (countryId == 0)
            {
                var methodName = nameof(this.Create).ToString();
                var controllerName = nameof(SalesController).Replace(GlobalConstants.ControllerAsString, string.Empty);
                var nameOfCountriesController = nameof(CountriesController).Replace(GlobalConstants.ControllerAsString, string.Empty);
                var nameOfSelectCountryActionInCountriesController = nameof(CountriesController.SelectCountry);

                return this.RedirectToAction(nameOfSelectCountryActionInCountriesController, nameOfCountriesController, new { methodName, controllerName });
            }

            var viewModel = await this.salesService.GetViewModelForCreateSale(countryId);

            return this.View(viewModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(AddSaleViewModel input, string captcha)
        {
            if (!await this.captchaValidator.IsCaptchaPassedAsync(captcha))
            {
                this.ModelState.AddModelError(GlobalConstants.ReCaptchaName, GlobalConstants.ReCaptchaErrorMessage);
            }

            if (!this.ModelState.IsValid)
            {
                input.CitiesItems = await this.citiesService.GetAllAsKeyValuePairsAsync(input.CountryId);
                input.Car = await this.carsService.GetCarInputModelWithFilledListItems();

                return this.View(input);
            }

            var user = await this.userManager.GetUserAsync(this.User);

            int id = 0;

            try
            {
                id = await this.salesService.CreateSaleAsync(input, user.Id);
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                input.CitiesItems = await this.citiesService.GetAllAsKeyValuePairsAsync(input.CountryId);
                input.Car = await this.carsService.GetCarInputModelWithFilledListItems();
                return this.View(input);
            }

            this.TempData["Message"] = GlobalConstants.SuccessfullyAddedSaleMessage;

            return this.RedirectToAction(nameof(this.SaleInfo), new { id });
        }

        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            var viewModel = await this.salesService.GetEditSaleViewModel(id);

            return this.View(viewModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditSaleInputModel input)
        {
            var user = await this.userManager.GetUserAsync(this.User);

            input.CountryId = user.CountryId;

            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            await this.salesService.UpdateSaleAsync(id, input);

            return this.RedirectToAction(nameof(this.SaleInfo), new { id });
        }

        public async Task<IActionResult> All(int id = 1)
        {
            int countryId;

            if (this.HttpContext.Session.Keys.Contains("CountryId"))
            {
                countryId = JsonConvert.DeserializeObject<int>(this.HttpContext.Session.GetString("CountryId"));
            }
            else if (this.User.Identity.IsAuthenticated)
            {
                var user = await this.userManager.GetUserAsync(this.User);
                countryId = user.CountryId;
            }
            else
            {
                var methodName = nameof(this.All).ToString();
                var controllerName = nameof(SalesController).Replace(GlobalConstants.ControllerAsString, string.Empty);
                var nameOfCountriesController = nameof(CountriesController).Replace(GlobalConstants.ControllerAsString, string.Empty);
                var nameOfSelectCountryActionInCountriesController = nameof(CountriesController.SelectCountry);

                return this.RedirectToAction(nameOfSelectCountryActionInCountriesController, nameOfCountriesController, new { methodName, controllerName });
            }

            const int ItemsPerPage = 12;

            var viewModel = await this.salesService.GetSalesListViewModelByCountryId(id, ItemsPerPage, countryId);

            return this.View(viewModel);
        }

        public async Task<IActionResult> AllByUserId(string id)
        {
            var viewModel = await this.salesService.GetSalesListViewModelByUserId(id);

            return this.View(viewModel);
        }

        public async Task<IActionResult> SaleInfo(int id)
        {
            var viewModel = await this.salesService.GetSingleSaleInfo(id);

            return this.View(viewModel);
        }

        [Authorize]
        public async Task<IActionResult> DeleteSale(int id)
        {
            await this.salesService.DeleteAsync(id);

            var nameOfUsersController = nameof(DashboardController).Replace(GlobalConstants.ControllerAsString, string.Empty);
            var nameOfAllActionInUsersController = nameof(DashboardController.Index);

            return this.RedirectToAction(nameOfAllActionInUsersController, nameOfUsersController);
        }
    }
}

src/Web/CarDealer.Web/Controllers/UsersController.cs
namespace CarDealer.Web.Controllers
{
    using System.Threading.Tasks;

    using CarDealer.Data.Models;
    using CarDealer.Services.Data;
    using CarDealer.Web.ViewModels.InputModels.Users;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class UsersController : BaseController
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IUsersService usersService;

        public UsersController(
            UserManager<ApplicationUser> userManager,
            IUsersService usersService)
        {
            this.userManager = userManager;
            this.usersService = usersService;
        }

        public async Task<IActionResult> UserInfo()
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var userViewModel = await this.usersService.GetUserById(user.Id);

            return this.View(userViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> UserInfo(UserInputModel input)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            await this.usersService.UpdateUserInfo(user.Id, input);

            var viewModel = await this.usersService.GetUserById(user.Id);

            return this.View(viewModel);
        }
    }
}

src/Web/CarDealer.Web/Views/Dashboard/index.cshtml
@model CarDealer.Web.ViewModels.Dashboard.DashboardViewModel

<section class="dashboard section">
    <!-- Container Start -->
    <div class="container">
        <!-- Row Start -->
        <div class="row">
            <div class="col-md-10 offset-md-1 col-lg-4 offset-lg-0">
                <div class="sidebar">
                    <!-- User Widget -->
                    <div class="widget user-dashboard-profile">
                        <!-- User Image -->
                        <div class="profile-thumb">
                            <img src="~/images/user/no-profile.jpg" alt="" class="rounded-circle">
                        </div>
                        <!-- User Name -->
                        <h5 class="text-center">@Model.UserFirstName @Model.UserLastName</h5>
                        <p>Joined @Model.UserCreatedOnAsString</p>
                        <a href="/Identity/Account/Manage" class="btn btn-main-sm">Edit Profile</a>
                    </div>
                    <!-- Dashboard Links -->
                    <div class="widget user-dashboard-menu">
                        <ul>
                            <li class="active"><a asp-area="" asp-controller="Dashboard" asp-action="Index"><i class="fa fa-user"></i> My Ads</a></li>
                            <li>
                                <a href="" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fa fa-cog"></i>Logout
                                </a>
                            </li>
                            <li>
                                <a href="/Identity/Account/Manage/DeletePersonalData">
                                    <i class="fa fa-power-off"></i>Delete
                                    Account
                                </a>
                            </li>
                        </ul>
                        <form id="deleteUserForm" asp-area="" asp-controller="Users" asp-action="DeleteUser" style="display: none;">
                            <button type="submit" name="deleteUser" id="deleteUser" value="Log Out">Delete User</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-0">
                <!-- Recently Favorited -->
                <div class="widget dashboard-container my-adslist">
                    <h3 class="widget-header">My Cars</h3>
                    <table class="table table-responsive product-dashboard-table">
                        <thead>
                            <tr>
                                <th>Image</th>
                                <th>CAR INFO</th>
                                <th class="text-center">Category</th>
                                <th class="text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var sale in Model.Sales)
                            {
                                <tr>

                                    <td class="product-thumb">
                                        <img width="80px" height="auto" src=@sale.ResizedImageUrls.FirstOrDefault() alt="image description">
                                    </td>
                                    <td class="product-details">
                                        <h3 class="title">@sale.Car.MakeName @sale.Car.ModelName</h3>
                                        <span><strong>Posted on: </strong><time>@sale.CreatedOn.Day/@sale.CreatedOn.Month/@sale.CreatedOn.Year</time> </span>
                                        <span class="location"><strong>Location</strong>@sale.CityName, @sale.CountryName</span>
                                    </td>
                                    <td class="product-category"><span class="categories">@sale.Car.CategoryName</span></td>
                                    <td class="action" data-title="Action">
                                        <div class="">
                                            <ul class="list-inline justify-content-center">
                                                <li class="list-inline-item">
                                                    <a data-toggle="tooltip" data-placement="top" title="view" class="view" asp-action="SaleInfo" asp-controller="Sales" asp-route-id="@sale.Id">
                                                        <i class="fa fa-eye"></i>
                                                    </a>
                                                </li>
                                                <li class="list-inline-item">
                                                    <a class="edit" data-toggle="tooltip" data-placement="top" title="Edit" asp-action="Edit" asp-controller="Sales" asp-route-id="@sale.Id">
                                                        <i class="fa fa-pencil"></i>
                                                    </a>
                                                </li>
                                                <li class="list-inline-item">
                                                    <a class="delete" data-toggle="tooltip" data-placement="top" title="Delete" asp-action="DeleteSale" asp-controller="Sales" asp-route-id="@sale.Id">
                                                        <i class="fa fa-trash"></i>
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- Row End -->
    </div>
    <!-- Container End -->
</section>

<!-- Logout Modal -->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header border-bottom-0">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body text-center">
                <img src="images/account/logout.png" class="img-fluid mb-2" alt="">
                <h6 class="py-2">Are you sure you want to logout?</h6>
            </div>
            <div class="modal-footer border-top-0 mb-3 mx-5 justify-content-lg-between justify-content-center">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                <button onclick="document.getElementById('logoutForm').submit()" type="button" class="btn btn-danger">Logout</button>
            </div>
        </div>
    </div>
</div>