src/Web/CarDealer.Web/Areas/Administration/Controllers/SalesController.cs
namespace CarDealer.Web.Areas.Administration.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using CarDealer.Data.Common.Repositories;
    using CarDealer.Data.Models;
    using CarDealer.Data.Models.SaleModels;
    using CarDealer.Services.Data;
    using CarDealer.Web.ViewModels.Sales;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.EntityFrameworkCore;

    [Area("Administration")]
    public class SalesController : AdministrationController
    {
        private readonly IDeletableEntityRepository<Sale> salesRepository;
        private readonly IDeletableEntityRepository<Car> carsRepository;
        private readonly IDeletableEntityRepository<ApplicationUser> usersRepository;
        private readonly IRepository<Country> countriesRepository;
        private readonly ISalesService salesService;

        public SalesController(
            IDeletableEntityRepository<Sale> salesRepository,
            IDeletableEntityRepository<Car> carsRepository,
            IDeletableEntityRepository<ApplicationUser> usersRepository,
            IRepository<Country> countriesRepository,
            ISalesService salesService)
        {
            this.salesRepository = salesRepository;
            this.carsRepository = carsRepository;
            this.usersRepository = usersRepository;
            this.countriesRepository = countriesRepository;
            this.salesService = salesService;
        }

        // GET: Administration/Sales
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = this.salesRepository.All().Include(s => s.Car).Include(s => s.Country).Include(s => s.User);
            var sales = await applicationDbContext.ToListAsync();

            var viewModel = new List<SaleViewModel>();

            foreach (var sale in sales)
            {
                viewModel.Add(await this.salesService.GetSingleSaleInfo(sale.Id));
            }

            return this.View(viewModel);
        }

        // GET: Administration/Sales/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var sale = await this.salesRepository.All()
                .Include(s => s.Car)
                .Include(s => s.Country)
                .Include(s => s.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sale == null)
            {
                return this.NotFound();
            }

            return this.View(sale);
        }

        // GET: Administration/Sales/Create
        public IActionResult Create()
        {
            this.ViewData["CarId"] = new SelectList(this.carsRepository.All(), "Id", "Id");
            this.ViewData["CountryId"] = new SelectList(this.countriesRepository.All(), "Id", "Id");
            this.ViewData["UserId"] = new SelectList(this.usersRepository.All(), "Id", "Id");
            return this.View();
        }

        // POST: Administration/Sales/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DaysValid,CarId,Price,CountryId,UserId,Description,IsDeleted,DeletedOn,Id,CreatedOn,ModifiedOn")] Sale sale)
        {
            if (this.ModelState.IsValid)
            {
                await this.salesRepository.AddAsync(sale);
                await this.salesRepository.SaveChangesAsync();
                return this.RedirectToAction(nameof(this.Index));
            }

            this.ViewData["CarId"] = new SelectList(this.carsRepository.All(), "Id", "Id", sale.CarId);
            this.ViewData["CountryId"] = new SelectList(this.countriesRepository.All(), "Id", "Id", sale.CountryId);
            this.ViewData["UserId"] = new SelectList(this.usersRepository.All(), "Id", "Id", sale.UserId);
            return this.View(sale);
        }

        // GET: Administration/Sales/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var sale = await this.salesRepository.All().FirstOrDefaultAsync(x => x.Id == id);
            if (sale == null)
            {
                return this.NotFound();
            }

            this.ViewData["CarId"] = new SelectList(this.carsRepository.All(), "Id", "Id", sale.CarId);
            this.ViewData["CountryId"] = new SelectList(this.countriesRepository.All(), "Id", "Id", sale.CountryId);
            this.ViewData["UserId"] = new SelectList(this.usersRepository.All(), "Id", "Id", sale.UserId);
            return this.View(sale);
        }

        // POST: Administration/Sales/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DaysValid,CarId,Price,CountryId,UserId,Description,IsDeleted,DeletedOn,Id,CreatedOn,ModifiedOn")] Sale sale)
        {
            if (id != sale.Id)
            {
                return this.NotFound();
            }

            if (this.ModelState.IsValid)
            {
                try
                {
                    this.salesRepository.Update(sale);
                    await this.salesRepository.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!this.SaleExists(sale.Id))
                    {
                        return this.NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return this.RedirectToAction(nameof(this.Index));
            }

            this.ViewData["CarId"] = new SelectList(this.carsRepository.All(), "Id", "Id", sale.CarId);
            this.ViewData["CountryId"] = new SelectList(this.countriesRepository.All(), "Id", "Id", sale.CountryId);
            this.ViewData["UserId"] = new SelectList(this.usersRepository.All(), "Id", "Id", sale.UserId);
            return this.View(sale);
        }

        // GET: Administration/Sales/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var sale = await this.salesRepository.All()
                .Include(s => s.Car)
                .Include(s => s.Country)
                .Include(s => s.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sale == null)
            {
                return this.NotFound();
            }

            return this.View(sale);
        }

        // POST: Administration/Sales/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sale = await this.salesRepository.All().FirstOrDefaultAsync(x => x.Id == id);
            this.salesRepository.Delete(sale);
            await this.salesRepository.SaveChangesAsync();
            return this.RedirectToAction(nameof(this.Index));
        }

        private bool SaleExists(int id)
        {
            return this.salesRepository.All().Any(e => e.Id == id);
        }
    }
}

src/Web/CarDealer.Web/Controllers/SearchSalesController.cs
namespace CarDealer.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using CarDealer.Common;
    using CarDealer.Data.Models;
    using CarDealer.Services.Data;
    using CarDealer.Web.ViewModels.InputModels.SearchSales;
    using CarDealer.Web.ViewModels.Sales;

    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    using Newtonsoft.Json;

    public class SearchSalesController : BaseController
    {
        private readonly ISalesService salesService;
        private readonly ICategoriesService categoriesService;
        private readonly IMakesService makesService;
        private readonly IModelsService modelsService;
        private readonly IFuelTypesService fuelTypesService;
        private readonly IEuroStandartsService euroStandartsService;
        private readonly IGearboxesService gearboxesService;
        private readonly IColorsService colorsService;
        private readonly ICountriesService countriesService;
        private readonly ICitiesService citiesService;
        private readonly UserManager<ApplicationUser> userManager;

        public SearchSalesController(
            ISalesService salesService,
            ICategoriesService categoriesService,
            IMakesService makesService,
            IModelsService modelsService,
            IFuelTypesService fuelTypesService,
            IEuroStandartsService euroStandartsService,
            IGearboxesService gearboxesService,
            IColorsService colorsService,
            ICountriesService countriessService,
            ICitiesService citiesService,
            UserManager<ApplicationUser> userManager)
        {
            this.salesService = salesService;
            this.categoriesService = categoriesService;
            this.makesService = makesService;
            this.modelsService = modelsService;
            this.fuelTypesService = fuelTypesService;
            this.euroStandartsService = euroStandartsService;
            this.gearboxesService = gearboxesService;
            this.colorsService = colorsService;
            this.countriesService = countriessService;
            this.citiesService = citiesService;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Index(int countryId)
        {
            if (this.HttpContext.Session.Keys.Contains("CountryId"))
            {
                countryId = JsonConvert.DeserializeObject<int>(this.HttpContext.Session.GetString("CountryId"));
            }
            else if (this.User.Identity.IsAuthenticated)
            {
                var user = await this.userManager.GetUserAsync(this.User);
                countryId = user.CountryId;
            }
            else
            {
                var methodName = nameof(this.Index).ToString();
                var controllerName = nameof(SearchSalesController).Replace(GlobalConstants.ControllerAsString, string.Empty);
                var nameOfCountriesController = nameof(CountriesController).Replace(GlobalConstants.ControllerAsString, string.Empty);
                var nameOfSelectCountryActionInCountriesController = nameof(CountriesController.SelectCountry);

                return this.RedirectToAction(nameOfSelectCountryActionInCountriesController, nameOfCountriesController, new { methodName, controllerName });
            }

            this.TempData["CountryId"] = countryId;

            var viewModel = await this.GetSearchListInputModelWithFilledProperties(countryId);

            return this.View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> List(SearchListInputModel input)
        {
            var salesListViewModel = new SalesListViewModel();

            salesListViewModel.Sales = await this.salesService.GetAllBySearchForm(input);

            return this.View(salesListViewModel);
        }

        public async Task<SearchListInputModel> GetSearchListInputModelWithFilledProperties(int countryId)
        {
            var carViewModel = new SearchListInputModel
            {
                CountryId = countryId,
                CategoriesItems = await this.categoriesService.GetAllAsKeyValuePairsAsync(),
                MakesItems = await this.makesService.GetAllAsKeyValuePairsAsync(),
                FuelTypeItems = await this.fuelTypesService.GetAllAsKeyValuePairsAsync(),
                EuroStandartItems = await this.euroStandartsService.GetAllAsKeyValuePairsAsync(),
                GearboxesItems = await this.gearboxesService.GetAllAsKeyValuePairsAsync(),
                ColorstItems = await this.colorsService.GetAllAsKeyValuePairsAsync(),
                CitiesItems = await this.citiesService.GetAllAsKeyValuePairsAsync(countryId),
                CountriesItems = await this.countriesService.GetAllAsKeyValuePairsAsync(),
            };

            return carViewModel;
        }
    }
}

src/Web/CarDealer.Web/Views/Sales/All.cshtml
@model CarDealer.Web.ViewModels.Sales.SalesListViewModel

@if (Model.Sales.Count() == 0)
{
    <section>
        <div class="container">
            <div class="text-center">
                <h1>Car Listing</h1>

                <br>

                <p class="lead">You don't have any car in your country.</p>
            </div>
        </div>
    </section>
}
else
{
    <section>
        <div  id="cars">
            <div class="col-md-12 col-sm-12">
                <div class="section-title text-center">
                    <h2>All cars in your country.</h2>
                </div>
                <br />
                <form>
                    <div style="text-align:center">
                        <button class="button-search" style="vertical-align:middle;" asp-controller="SearchSales" asp-action="Index"><span>Search cars </span></button>
                    </div>
                </form>
            </div>
            <br />

            <div class="product-grid-list">
                <div class="row mt-30">
                    @foreach (var sale in Model.Sales)
                    {
                        <div class="col-sm-12 col-lg-3">
                            <!-- product card -->
                            <div class="product-item bg-light">
                                <div class="card">
                                    <div class="thumb-content">
                                        <div class="price">$@sale.Price</div>
                                        <a asp-action="SaleInfo" asp-controller="Sales" asp-route-id="@sale.Id">
                                            <img class="card-img-top img-fluid" src="@sale.ResizedImageUrls.FirstOrDefault()" alt="Card image cap">
                                        </a>
                                    </div>
                                    <div class="card-body">
                                        <h4 class="card-title"><a asp-action="SaleInfo" asp-controller="Sales" asp-route-id="@sale.Id">@sale.Car.MakeName @sale.Car.ModelName</a></h4>
                                        <ul class="list-inline product-meta">
                                            <li class="list-inline-item">
                                                <a href="#"><i class="fa fa-calendar"></i>@sale.CreatedOn.Day/@sale.CreatedOn.Month/@sale.CreatedOn.Year</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
                <hr />
                <partial name="_PagingPartial" model="@Model" />
                <hr />
            </div>
        </div>
    </section>
}

src/Web/CarDealer.Web/Views/Sales/AllByUserId.cshtml
@model IEnumerable<CarDealer.Web.ViewModels.Sales.SaleViewModel>

<section>
    <div id="cars">
        <br />
        <div class="product-grid-list">
            <div class="row mt-30">
                @foreach (var sale in Model)
                {
                    <div class="col-sm-12 col-lg-3">
                        <!-- product card -->
                        <div class="product-item bg-light">
                            <div class="card">
                                <div class="thumb-content">
                                    <div class="price">$@sale.Price</div>
                                    <a asp-action="SaleInfo" asp-controller="Sales" asp-route-id="@sale.Id">
                                        <img class="card-img-top img-fluid" src="@sale.ResizedImageUrls.FirstOrDefault()" alt="Card image cap">
                                    </a>
                                </div>
                                <div class="card-body">
                                    <h4 class="card-title"><a asp-action="SaleInfo" asp-controller="Sales" asp-route-id="@sale.Id">@sale.Car.MakeName @sale.Car.ModelName</a></h4>
                                    <ul class="list-inline product-meta">
                                        <li class="list-inline-item">
                                            <a href="#"><i class="fa fa-calendar"></i>@sale.CreatedOn.Day/@sale.CreatedOn.Month/@sale.CreatedOn.Year</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>

src/Web/CarDealer.Web/Views/Sales/SaleInfo.cshtml
@model CarDealer.Web.ViewModels.Sales.SaleViewModel

@if (this.TempData.ContainsKey("Message"))
{
    <div class="alert alert-success alert-dismissable">@this.TempData["Message"]</div>
}

<section class="section bg-gray">
    <!-- Container Start -->
    <div class="container">
        <div class="row">
            <!-- Left sidebar -->
            <div class="col-md-8">
                <div class="product-details">
                    <h1 class="product-title">@Model.Car.MakeName @Model.Car.ModelName </h1>
                    <div class="product-meta">
                        <ul class="list-inline">
                            <li class="list-inline-item"><i class="fa fa-user-o"></i> By <a href="">@Model.UserName</a></li>
                            <li class="list-inline-item"><i class="fa fa-folder-open-o"></i> Category<a href="">@Model.Car.CategoryName</a></li>
                            <li class="list-inline-item"><i class="fa fa-location-arrow"></i> Location<a href="">@Model.CityName, @Model.CountryName</a></li>
                            <li class="list-inline-item"><i class="fa fa-eye"></i><a href="">@Model.OpensSaleCounter</a></li>
                        </ul>
                    </div>

                    <!-- product slider -->
                    <div class="product-slider">
                        <div class="product-slider-item my-4" data-image="@Model.ResizedImageUrls.FirstOrDefault()">
                            <img class="img-fluid w-100" src="@Model.ResizedImageUrls.FirstOrDefault()" alt="product-img" style="padding-bottom: 50px;">
                        </div>
                        @if (Model.ResizedImageUrls.Count() > 0)
                        {
                            @foreach (var imgUrl in Model.ResizedImageUrls.Skip(1))
                            {
                                <div class="product-slider-item my-4" data-image=@imgUrl>
                                    <img class="d-block img-fluid w-100" src=@imgUrl alt="Second slide">
                                </div>
                            }
                        }
                    </div>
                    <!-- product slider -->

                    <div class="content mt-5 pt-5">
                        <ul class="nav nav-pills  justify-content-center" id="pills-tab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home"
                                   aria-selected="true">Description</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile"
                                   aria-selected="false">Specifications</a>
                            </li>
                            @if (Model.Car.Extras.Count() > 0)
                            {
                                <li class="nav-item">
                                    <a class="nav-link" id="pills-contact-tab" data-toggle="pill" href="#pills-contact" role="tab" aria-controls="pills-contact"
                                       aria-selected="false">Extras</a>
                                </li>
                            }
                        </ul>
                        <div class="tab-content" id="pills-tabContent">
                            <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
                                <p>
                                    @Model.Description
                                </p>
                            </div>
                            <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
                                <h3 class="tab-title">Product Specifications</h3>
                                <table class="table table-bordered product-table">
                                    <tbody>
                                        <tr>
                                            <td>Added</td>
                                            <td>@Model.CreatedOn.Day/@Model.CreatedOn.Month/@Model.CreatedOn.Year</td>
                                        </tr>
                                        <tr>
                                            <td>Seller Price</td>
                                            <td>@Model.Price €</td>
                                        </tr>
                                        <tr>
                                            <td>Manufacture date</td>
                                            <td>@Model.Car.ManufactureDate.Day/@Model.Car.ManufactureDate.Month/@Model.Car.ManufactureDate.Year</td>
                                        </tr>
                                        <tr>
                                            <td>Location</td>
                                            <td>@Model.CityName, @Model.CountryName</td>
                                        </tr>
                                        <tr>
                                            <td>Brand</td>
                                            <td>@Model.Car.MakeName</td>
                                        </tr>
                                        <tr>
                                            <td>Model</td>
                                            <td>@Model.Car.ModelName</td>
                                        </tr>
                                        <tr>
                                            <td>Condition</td>
                                            <td>@Model.Car.State.ToString()</td>
                                        </tr>
                                        <tr>
                                            <td>Mileage</td>
                                            <td>@Model.Car.Mileage km</td>
                                        </tr>
                                        <tr>
                                            <td>Fuel type</td>
                                            <td>@Model.Car.FuelTypeName</td>
                                        </tr>
                                        <tr>
                                            <td>Engine size</td>
                                            <td>@Model.Car.EngineSize cc</td>
                                        </tr>
                                        <tr>
                                            <td>Horse power</td>
                                            <td>@Model.Car.HorsePower hp</td>
                                        </tr>
                                        <tr>
                                            <td>Euro standart</td>
                                            <td>@Model.Car.EuroStandartId</td>
                                        </tr>
                                        <tr>
                                            <td>Gearbox</td>
                                            <td>@Model.Car.GearboxName</td>
                                        </tr>
                                        <tr>
                                            <td>Seats</td>
                                            <td>@Model.Car.Seats</td>
                                        </tr>
                                        <tr>
                                            <td>Doors</td>
                                            <td>@Model.Car.Doors</td>
                                        </tr>
                                        <tr>
                                            <td>Color</td>
                                            <td>@Model.Car.ColorName</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
                                <h2>Car extras:</h2>
                                <div class="product-review">
                                    @foreach (var extra in Model.Car.Extras)
                                    {
                                        <p>@extra</p>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="sidebar">
                    <div class="widget price text-center">
                        <h4>Price</h4>
                        <p>@Model.Price €</p>
                    </div>
                    <!-- User Profile widget -->
                    <div class="widget user text-center">
                        <h4><a href="">@Model.UserName</a></h4>
                        <h4><a href="">@Model.UserEmail</a></h4>
                        <h4><a href="">@Model.UserPhoneNumber</a></h4>
                        <p class="member-time">Member Since Jun 27, 2017</p>
                        <a asp-controller="Sales" asp-action="AllByUserId" asp-route-id="@Model.UserId">See all ads</a>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- Container End -->
</section>